services:
  - type: web
    name: telegram-downloader-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python main.py
    region: oregon
    branch: main
    autoDeploy: true
